import type { Complaint, ComplaintCategory, ComplaintStatus, Priority } from '@/types';

/**
 * Demo complaints seeded from the Civic_Survey_Data CSV for realistic prototype data.
 * These represent real issues from the MMR/Pune survey.
 */
const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: 'c001',
    ticketNumber: 'SMV-2026-00001',
    title: 'Overflowing garbage bins near Palghar station',
    description: 'Multiple garbage bins overflowing for 3 days near Palghar railway station. Causing foul smell and health hazard to commuters. Dogs and stray animals scattering waste.',
    category: 'garbage',
    status: 'pending',
    priority: 'high',
    ward: 'Palghar Ward 3',
    city: 'Mumbai Metropolitan Region',
    area: 'Palghar',
    address: 'Near Palghar Railway Station, Platform Road',
    geoLocation: { latitude: 19.6967, longitude: 72.7699, accuracy: 15, timestamp: Date.now() - 86400000 * 3 },
    media: [],
    citizenId: 'citizen-001',
    citizenName: 'Ramesh Patil',
    followUps: [],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    slaDays: 3,
    isOverdue: true,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c002',
    ticketNumber: 'SMV-2026-00002',
    title: 'Broken water pipeline causing flooding in Virar',
    description: 'A major water pipeline has burst on the main road causing water logging and traffic disruption. Water is being wasted for the past 2 days. Residents unable to get proper water supply.',
    category: 'water-supply',
    status: 'verified',
    priority: 'critical',
    ward: 'Virar Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Virar',
    address: 'Main Road, near Virar Bus Depot',
    geoLocation: { latitude: 19.4559, longitude: 72.8115, accuracy: 10, timestamp: Date.now() - 86400000 * 2 },
    media: [],
    citizenId: 'citizen-002',
    citizenName: 'Suresh Kumar',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000).toISOString(),
    followUps: [
      {
        id: 'f001',
        complaintId: 'c002',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Visited the site. Confirmed the pipeline burst. Water is flooding the road. Municipal workers not yet present. Alerting the ward office.',
        createdAt: new Date(Date.now() - 86400000).toISOString(),
        type: 'verification',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    slaDays: 2,
    isOverdue: true,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c003',
    ticketNumber: 'SMV-2026-00003',
    title: 'Dangerous potholes on Boisar highway',
    description: 'Multiple deep potholes on the main highway near Boisar. Two accidents reported this week. Extremely dangerous for two-wheeler riders especially at night.',
    category: 'road-conditions',
    status: 'in-progress',
    priority: 'critical',
    ward: 'Boisar Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Boisar',
    address: 'National Highway, near Boisar MIDC',
    geoLocation: { latitude: 19.8014, longitude: 72.7553, accuracy: 20, timestamp: Date.now() - 86400000 * 5 },
    media: [],
    citizenId: 'citizen-003',
    citizenName: 'Meera Joshi',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    followUps: [
      {
        id: 'f002',
        complaintId: 'c003',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Site verified. Counted 8 major potholes in a 500m stretch. Took photos and videos as evidence. Very dangerous.',
        createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
        type: 'verification',
      },
      {
        id: 'f003',
        complaintId: 'c003',
        authorId: 'admin-001',
        authorName: 'Dr. Anita Deshmukh',
        authorRole: 'admin',
        content: 'Escalated to PWD department. Repair work scheduled for next week. Assigned contractor.',
        createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        type: 'status-update',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    slaDays: 7,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c004',
    ticketNumber: 'SMV-2026-00004',
    title: 'Street lights not working in Kelve residential area',
    description: 'All street lights in the Kelve residential colony (Sector 4) have been non-functional for over a week. Senior citizens are afraid to walk after dark. Multiple robbery attempts reported.',
    category: 'street-lighting',
    status: 'resolved',
    priority: 'high',
    ward: 'Kelve Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Kelve',
    address: 'Sector 4, Kelve Residential Colony',
    geoLocation: { latitude: 19.6167, longitude: 72.7167, accuracy: 25, timestamp: Date.now() - 86400000 * 10 },
    media: [],
    citizenId: 'citizen-004',
    citizenName: 'Govind Nair',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    resolvedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    followUps: [
      {
        id: 'f004',
        complaintId: 'c004',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Verified. 12 street lights not working in the stretch. Reported to electrical department.',
        createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
        type: 'verification',
      },
      {
        id: 'f005',
        complaintId: 'c004',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'All 12 street lights have been repaired and are now functional. Verified on-site at 8 PM.',
        createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
        type: 'resolution',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    slaDays: 5,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c005',
    ticketNumber: 'SMV-2026-00005',
    title: 'Sewage overflow in Borivali West',
    description: 'Sewage water overflowing from manhole covers on Link Road. Dirty water entering shops and ground-floor houses. Health risk for residents.',
    category: 'drainage',
    status: 'escalated',
    priority: 'critical',
    ward: 'Borivali Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Borivali',
    address: 'Link Road, Borivali West, near IC Colony',
    geoLocation: { latitude: 19.2288, longitude: 72.8544, accuracy: 12, timestamp: Date.now() - 86400000 * 7 },
    media: [],
    citizenId: 'citizen-005',
    citizenName: 'Fatima Sheikh',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    escalatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    followUps: [
      {
        id: 'f006',
        complaintId: 'c005',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Situation is critical. Multiple manholes overflowing. The entire stretch smells terrible.',
        createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
        type: 'verification',
      },
      {
        id: 'f007',
        complaintId: 'c005',
        authorId: 'admin-001',
        authorName: 'Dr. Anita Deshmukh',
        authorRole: 'admin',
        content: 'Escalating to BMC Commissioner office. 4 days overdue. This is a public health emergency.',
        createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
        type: 'escalation',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    slaDays: 4,
    isOverdue: true,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c006',
    ticketNumber: 'SMV-2026-00006',
    title: 'Industrial pollution in Bhayandar creek',
    description: 'Chemical waste being discharged into the creek from nearby industrial units. Water has turned dark and foul-smelling. Fish kill observed. Affecting fishing community livelihood.',
    category: 'pollution',
    status: 'in-progress',
    priority: 'high',
    ward: 'Bhayandar Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Bhayandar',
    address: 'Creek Road, Bhayandar East',
    geoLocation: { latitude: 19.2963, longitude: 72.8518, accuracy: 30, timestamp: Date.now() - 86400000 * 4 },
    media: [],
    citizenId: 'citizen-006',
    citizenName: 'Anil Koli',
    followUps: [],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    slaDays: 10,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c007',
    ticketNumber: 'SMV-2026-00007',
    title: 'Garbage dumping at open plot in Mira Road',
    description: 'Residents dumping garbage at an open plot near the temple. No municipal bins available. The area has become a breeding ground for mosquitoes.',
    category: 'garbage',
    status: 'pending',
    priority: 'medium',
    ward: 'Mira Road Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Mira Road',
    address: 'Near Shiv Temple, Sector 5, Mira Road',
    geoLocation: { latitude: 19.2816, longitude: 72.8726, accuracy: 18, timestamp: Date.now() - 86400000 },
    media: [],
    citizenId: 'citizen-001',
    citizenName: 'Ramesh Patil',
    followUps: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    slaDays: 3,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c008',
    ticketNumber: 'SMV-2026-00008',
    title: 'No water supply for 48 hours in Vasai',
    description: 'Our area has had no water supply for 2 days. The municipal office says there is a pipeline repair but no timeline given. Families with elderly and children are suffering.',
    category: 'water-supply',
    status: 'verified',
    priority: 'high',
    ward: 'Vasai Ward 2',
    city: 'Mumbai Metropolitan Region',
    area: 'Vasai',
    address: 'Vasai West, Rajawadi Colony',
    geoLocation: { latitude: 19.3607, longitude: 72.8362, accuracy: 22, timestamp: Date.now() - 86400000 * 2 },
    media: [],
    citizenId: 'citizen-007',
    citizenName: 'Kavita Rane',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000).toISOString(),
    followUps: [
      {
        id: 'f008',
        complaintId: 'c008',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Confirmed no water supply. Spoke with 10 families. All confirm 48+ hours. Municipal tanker has not visited.',
        createdAt: new Date(Date.now() - 86400000).toISOString(),
        type: 'verification',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    slaDays: 2,
    isOverdue: true,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c009',
    ticketNumber: 'SMV-2026-00009',
    title: 'Broken footpath tiles in Dahisar market area',
    description: 'Several footpath tiles are broken and uneven near Dahisar market. Senior citizens and wheelchair users cannot use the footpath safely.',
    category: 'road-conditions',
    status: 'pending',
    priority: 'medium',
    ward: 'Dahisar Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Dahisar',
    address: 'Market Road, Dahisar West',
    geoLocation: { latitude: 19.2568, longitude: 72.8628, accuracy: 15, timestamp: Date.now() - 86400000 * 1.5 },
    media: [],
    citizenId: 'citizen-008',
    citizenName: 'Deepak Mehta',
    followUps: [],
    createdAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    slaDays: 7,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c010',
    ticketNumber: 'SMV-2026-00010',
    title: 'Drainage blocked causing waterlogging in Kandivali',
    description: 'Heavy drain blockage causing waterlogging on the main road during every rain. Shops getting flooded. Mosquito breeding has increased.',
    category: 'drainage',
    status: 'in-progress',
    priority: 'high',
    ward: 'Kandivali Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Kandivali',
    address: 'SV Road, Kandivali West',
    geoLocation: { latitude: 19.2048, longitude: 72.8369, accuracy: 14, timestamp: Date.now() - 86400000 * 6 },
    media: [],
    citizenId: 'citizen-009',
    citizenName: 'Sanjay Gupta',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    followUps: [
      {
        id: 'f009',
        complaintId: 'c010',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Drain is completely blocked with plastic waste and construction debris. Municipal team has started clearing work.',
        createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
        type: 'status-update',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    slaDays: 4,
    isOverdue: true,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c011',
    ticketNumber: 'SMV-2026-00011',
    title: 'Street lights flickering in Malad',
    description: 'Street lights on the main road are flickering constantly at night. Very disturbing for residents and dangerous for drivers.',
    category: 'street-lighting',
    status: 'pending',
    priority: 'low',
    ward: 'Malad Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Malad',
    address: 'Malad West, Marve Road',
    geoLocation: { latitude: 19.1863, longitude: 72.8334, accuracy: 20, timestamp: Date.now() - 86400000 * 0.5 },
    media: [],
    citizenId: 'citizen-010',
    citizenName: 'Priti Desai',
    followUps: [],
    createdAt: new Date(Date.now() - 86400000 * 0.5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 0.5).toISOString(),
    slaDays: 5,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
  {
    id: 'c012',
    ticketNumber: 'SMV-2026-00012',
    title: 'Air pollution from construction site in Andheri',
    description: 'Massive construction project not following dust control norms. Entire neighborhood covered in dust. Residents reporting breathing problems.',
    category: 'pollution',
    status: 'verified',
    priority: 'high',
    ward: 'Andheri Ward 1',
    city: 'Mumbai Metropolitan Region',
    area: 'Andheri',
    address: 'Andheri East, MIDC Road',
    geoLocation: { latitude: 19.1136, longitude: 72.8697, accuracy: 25, timestamp: Date.now() - 86400000 * 3 },
    media: [],
    citizenId: 'citizen-011',
    citizenName: 'Rashid Khan',
    assignedVolunteerId: 'volunteer-001',
    assignedVolunteerName: 'Priya Sharma',
    verifiedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    followUps: [
      {
        id: 'f010',
        complaintId: 'c012',
        authorId: 'volunteer-001',
        authorName: 'Priya Sharma',
        authorRole: 'volunteer',
        content: 'Visited site. No dust barriers, no water sprinklers being used. Collected photo evidence. Construction company not compliant.',
        createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        type: 'verification',
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    slaDays: 10,
    isOverdue: false,
    syncStatus: 'synced',
    offlineCreated: false,
  },
];

export function getSeedComplaints(): Complaint[] {
  return DEMO_COMPLAINTS;
}

export function getComplaintById(id: string): Complaint | undefined {
  return DEMO_COMPLAINTS.find((c) => c.id === id);
}

/**
 * Get unique categories with counts from demo data.
 */
export function getCategoryCounts(): Record<ComplaintCategory, number> {
  const counts: Record<string, number> = {};
  DEMO_COMPLAINTS.forEach((c) => {
    counts[c.category] = (counts[c.category] || 0) + 1;
  });
  return counts as Record<ComplaintCategory, number>;
}

/**
 * Get status distribution from demo data.
 */
export function getStatusCounts(): Record<ComplaintStatus, number> {
  const counts: Record<string, number> = {};
  DEMO_COMPLAINTS.forEach((c) => {
    counts[c.status] = (counts[c.status] || 0) + 1;
  });
  return counts as Record<ComplaintStatus, number>;
}

/**
 * Get priority distribution.
 */
export function getPriorityCounts(): Record<Priority, number> {
  const counts: Record<string, number> = {};
  DEMO_COMPLAINTS.forEach((c) => {
    counts[c.priority] = (counts[c.priority] || 0) + 1;
  });
  return counts as Record<Priority, number>;
}
